### ISSUE TITLE
include Bootstrap framework

### ISSUE THREAD

**Issue by nunodotferreira** [flovan/headstart-boilerplate#2]
Hi
is there a way to include the Bootstrap framework!?

**Comment by flovan** [comment]
While I haven't tried it yet, it _should_ work.

You can use [these Bootstrap CDN links](http://getbootstrap.com/getting-started/#download-cdn), which you'll have to copy&paste into either the `header.html` or `footer.html` files, below the injection tags.

Or ...
- Download Bootstrap (you will need the contents of the [dist folder](https://github.com/twbs/bootstrap/tree/master/dist))
- Take the unminified files from the `css` folder, change their extension to `.scss` and either (don't do both):
  - drop them into the `assets/sass` folder to have them included as separate files
  - drop them into `assets/sass/libs`, prefix them with `_` (e.g. `_bootstrap.scss`) and `@import` them in `main.scss` to combine the files with it.
- Take the unminified files from the `js` folder and drop them into `assets/js/libs`
- Move the `fonts` folder to the `assets` folder.
- Restart the build process (e.g. on Mac use `cmd+c` to exit the process, then restart)

Let me know how it turned out!

**Comment by nunodotferreira** [comment]
Thanks Flovan, i'll try it and if it worked i'll let you know.

**Comment by nunodotferreira** [comment]
It worked, just can't get jQuery to work! any ideas?

**Comment by flovan** [comment]
Sure, in `assets/js/libs` do the following things:
- Prefix `ender.js` with an `_`
- Take out the `_` for the bundled `jquery-1.11.0.js`

This will put jQuery into your pages instead of the default Ender bundle.
Then, in `assets/js`:
- Change the domReady function in `main.js` (and any `view-*.js` file that you are actually using, so no `_` files) to the jQuery variant (you can find it commented out [on line 13](https://github.com/flovan/headstart-boilerplate/blob/master/assets/js/main.js#L13) by default)

Other than that, I'd have to see your setup, because it's hard to tell otherwise.

**Comment by nunodotferreira** [comment]
Hi Flovan,

many tanks, i've been seen your's headstart-website and now i understand.

meanwhile i'm working on it!

**Comment by flovan** [comment]
No problem at all. It might be a sign that the docs aren't that clear enough. Let me know if you got it working, and then I'll compare what I wrote in here with the docs when it's due for an update.

**Comment by nunodotferreira** [comment]
it all worked for me and made my own git repo https://github.com/nunodotferreira/headstart-bootstrap
hope it help

**Comment by flovan** [comment]
Ok nice! That's one framework confirmed working 👍
