### ISSUE TITLE
Headstart with browser-sync

### ISSUE THREAD

**Issue by karneaud** [flovan/headstart-boilerplate#4]
I Like how your framework is small and I find gulp and grunt boilerplates to be too unreliable sometimes for rapid flows. 

i however wanted to know about being able to plug in browser sync instead of the usual default server. What are your thoughts?

**Comment by flovan** [comment]
Hello @karneaud,

Funny that you ask, because Headstart is already using browser-sync internally! Perhaps there's anything missing that you'd like to be able to configure?

It is already possible to set a proxy and server port through the `config.json` file. For example by adding...

``` json
{
  "proxy": "http://localhost:8888"
}
```

... you'll end up with your regular localhost being mirrored (and synced) through the default 3000 port (which, again, can be changed as well).

Hope this helps!
- Florian

**Comment by karneaud** [comment]
wow cool
